[build.environment]

[build]
command = "npm run build"
publish = ".next"

[context.main]
command = "npm run build"
publish = ".next"

[context.deploy-preview]
command = "npm run build"
publish = ".next"
