server:
  port: '8080'

jwt:
  secret: 'your-generated-jwt-secret-here'
  refreshSecret: 'your-generated-refresh-secret-here'
  tokenExpiry: '15m'
  refreshExpiry: '72h'

database:
  # Uncomment and configure if using PostgreSQL
  # host: "localhost"
  # port: "5432"
  # user: "your_db_user"
  # password: "your_db_password"
  # dbname: "your_db_name"
  # sslmode: "disable"
