version: '3.9'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: ${DB_USER:-app}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-app}
      POSTGRES_DB: ${DB_NAME:-app}
    ports:
      - '5432:5432'
    volumes:
      - dbdata:/var/lib/postgresql/data
  app:
    build: .
    environment:
      DATABASE_URL: postgres://${DB_USER:-app}:${DB_PASSWORD:-app}@db:5432/${DB_NAME:-app}?sslmode=disable
      JWT_SECRET: ${JWT_SECRET:-dev-access-secret}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET:-dev-refresh-secret}
    ports:
      - '8080:8080'
    depends_on:
      - db
volumes:
  dbdata: {}
